import type { Logger } from "pino";
import type { PrismaClient } from "@prisma/client";
import type { Redis } from "ioredis";
import type { AppConfig } from "@config/index.js";
import type { IAuthService } from "@modules/auth/interfaces/IAuthService.js";
import type { IAuthRepository } from "@modules/auth/interfaces/IAuthRepository.js";
import type { IUserService } from "@modules/users/interfaces/IUserService.js";
import type { IUserRepository } from "@modules/users/interfaces/IUserRepository.js";
import type { IConversationService } from "@modules/conversations/interfaces/IConversationService.js";
import type { IConversationRepository } from "@modules/conversations/interfaces/IConversationRepository.js";
import type { IMessageService } from "@modules/messages/interfaces/IMessageService.js";
import type { IMessageRepository } from "@modules/messages/interfaces/IMessageRepository.js";
import type { IGroupService } from "@modules/groups/interfaces/IGroupService.js";
import type { IGroupRepository } from "@modules/groups/interfaces/IGroupRepository.js";
import type { IPresenceService } from "@modules/presence/interfaces/IPresenceService.js";
import type { IPresenceRepository } from "@modules/presence/interfaces/IPresenceRepository.js";
import type { IUploadService } from "@modules/uploads/interfaces/IUploadService.js";
import type { IUploadRepository } from "@modules/uploads/interfaces/IUploadRepository.js";
import type { IHealthService } from "@shared/interfaces/IHealthService.js";
import type { MetricsFacade, HealthMonitor } from "@observability/index.js";
import type { Tracer } from "@opentelemetry/api";
import type { AuthController } from "@modules/auth/controller/AuthController.js";
import type { UserController } from "@modules/users/controller/UserController.js";
import type { ConversationController } from "@modules/conversations/controller/ConversationController.js";
import type { MessageController } from "@modules/messages/controller/MessageController.js";
import type { GroupController } from "@modules/groups/controller/GroupController.js";
import type { PresenceController } from "@modules/presence/controller/PresenceController.js";
import type { UploadController } from "@modules/uploads/controller/UploadController.js";

/** Resolvable application dependencies (documentation / typing aid). */
export type AppDependencies = {
  config: AppConfig;
  logger: Logger;
  prisma: PrismaClient;
  redis: Redis;
  authService: IAuthService;
  authRepository: IAuthRepository;
  authController: AuthController;
  userService: IUserService;
  userRepository: IUserRepository;
  userController: UserController;
  conversationService: IConversationService;
  conversationRepository: IConversationRepository;
  conversationController: ConversationController;
  messageService: IMessageService;
  messageRepository: IMessageRepository;
  messageController: MessageController;
  groupService: IGroupService;
  groupRepository: IGroupRepository;
  groupController: GroupController;
  presenceService: IPresenceService;
  presenceRepository: IPresenceRepository;
  presenceController: PresenceController;
  uploadService: IUploadService;
  uploadRepository: IUploadRepository;
  uploadController: UploadController;
  healthService: IHealthService;
  metrics: MetricsFacade;
  healthMonitor: HealthMonitor;
  tracer: Tracer;
};
